// ─── Dish Profiles Static Data ─────────────────────────────────────────────
// Flavor axis scores: 0 = none/low, 10 = extremely strong
// Omitted axes default to 5 (neutral) in the scorer.
// Generated as a one-time batch; committed as static data (zero runtime API cost).

export type FlavorAxis =
  | 'umami'
  | 'richness'
  | 'spice'
  | 'bitter_char'
  | 'bright_acid'
  | 'sweet'
  | 'crispy'
  | 'silky'
  | 'chewy'
  | 'creamy'

export type DishFlavorProfile = Partial<Record<FlavorAxis, number>>

// ─── DISH PROFILES ───────────────────────────────────────────────────────────
// Key: lowercase, canonical dish name (fuzzy matched against input)

export const DISH_PROFILES: Record<string, DishFlavorProfile> = {
  // ── Japanese ──────────────────────────────────────────────────────────────
  'tonkotsu ramen': { umami: 9, richness: 9, spice: 1, bright_acid: 2, silky: 7, chewy: 6 },
  'shoyu ramen': { umami: 8, richness: 6, spice: 2, bright_acid: 3, chewy: 6 },
  'miso ramen': { umami: 9, richness: 7, spice: 2, sweet: 4, chewy: 6 },
  'spicy miso ramen': { umami: 9, richness: 7, spice: 7, chewy: 6 },
  'shio ramen': { umami: 7, richness: 5, spice: 1, bright_acid: 4 },
  'tantanmen': { umami: 8, richness: 8, spice: 7, chewy: 5 },
  'tsukemen': { umami: 9, richness: 8, spice: 2, chewy: 7 },
  'abura soba': { umami: 8, richness: 7, spice: 2, chewy: 7 },
  'ramen': { umami: 8, richness: 7, spice: 3, chewy: 6 },
  'udon': { umami: 6, richness: 4, spice: 1, chewy: 8 },
  'tempura udon': { umami: 6, richness: 5, spice: 1, chewy: 7, crispy: 6 },
  'kitsune udon': { umami: 6, richness: 4, sweet: 5, chewy: 7 },
  'yaki udon': { umami: 7, richness: 5, spice: 2, chewy: 7 },
  'soba': { umami: 5, richness: 3, spice: 1, bright_acid: 4, chewy: 6 },
  'zaru soba': { umami: 5, richness: 2, spice: 1, bright_acid: 5 },
  'yakisoba': { umami: 6, richness: 4, spice: 2, chewy: 5, sweet: 4 },
  'tempura': { umami: 5, richness: 5, spice: 1, crispy: 9 },
  'ebi tempura': { umami: 6, richness: 5, spice: 1, crispy: 9 },
  'vegetable tempura': { umami: 4, richness: 4, spice: 1, crispy: 8 },
  'katsu curry': { umami: 7, richness: 7, spice: 3, crispy: 7, sweet: 5 },
  'chicken katsu': { umami: 6, richness: 5, spice: 1, crispy: 8 },
  'tonkatsu': { umami: 6, richness: 6, spice: 1, crispy: 8 },
  'katsudon': { umami: 8, richness: 7, spice: 1, crispy: 5, sweet: 5 },
  'oyakodon': { umami: 7, richness: 6, spice: 1, sweet: 5, silky: 6 },
  'gyudon': { umami: 8, richness: 7, spice: 1, sweet: 5 },
  'donburi': { umami: 7, richness: 6, spice: 1, sweet: 4 },
  'unagi don': { umami: 8, richness: 7, spice: 1, sweet: 7, silky: 7 },
  'chirashi': { umami: 7, richness: 4, spice: 1, bright_acid: 5 },
  'sushi': { umami: 7, richness: 4, spice: 1, bright_acid: 5 },
  'nigiri': { umami: 7, richness: 3, spice: 1, bright_acid: 5 },
  'sashimi': { umami: 7, richness: 3, spice: 1, bright_acid: 4, silky: 7 },
  'tuna sashimi': { umami: 7, richness: 3, spice: 1, silky: 8 },
  'salmon sashimi': { umami: 6, richness: 6, spice: 1, silky: 8 },
  'yellowtail sashimi': { umami: 7, richness: 5, spice: 1, silky: 8 },
  'maki roll': { umami: 6, richness: 3, spice: 1, bright_acid: 4 },
  'spicy tuna roll': { umami: 7, richness: 4, spice: 6, bright_acid: 4 },
  'dragon roll': { umami: 6, richness: 6, spice: 3, sweet: 4, crispy: 4 },
  'rainbow roll': { umami: 7, richness: 5, spice: 2, silky: 6 },
  'california roll': { umami: 5, richness: 4, spice: 1, sweet: 3 },
  'philadelphia roll': { umami: 5, richness: 7, spice: 1, creamy: 7 },
  'edamame': { umami: 4, richness: 2, spice: 1 },
  'gyoza': { umami: 7, richness: 5, spice: 2, crispy: 6, chewy: 5 },
  'yaki gyoza': { umami: 7, richness: 5, spice: 2, crispy: 7, chewy: 5 },
  'shrimp gyoza': { umami: 6, richness: 4, spice: 1, crispy: 6 },
  'takoyaki': { umami: 7, richness: 6, spice: 1, crispy: 5, chewy: 6 },
  'okonomiyaki': { umami: 7, richness: 6, spice: 1, chewy: 5 },
  'yakitori': { umami: 7, richness: 4, spice: 2, bitter_char: 6, sweet: 5 },
  'negima yakitori': { umami: 7, richness: 4, spice: 1, bitter_char: 6, sweet: 5 },
  'tsukune': { umami: 7, richness: 5, spice: 1, bitter_char: 5, sweet: 5 },
  'karaage': { umami: 7, richness: 6, spice: 2, crispy: 9 },
  'agedashi tofu': { umami: 6, richness: 4, spice: 1, crispy: 5, silky: 6 },
  'miso soup': { umami: 7, richness: 3, spice: 1, silky: 4 },
  'tom kho tofu': { umami: 7, richness: 5, spice: 1, silky: 7 },
  'chawanmushi': { umami: 7, richness: 5, spice: 1, silky: 9 },
  'japanese curry': { umami: 7, richness: 7, spice: 3, sweet: 5 },
  'shabu shabu': { umami: 7, richness: 5, spice: 1, silky: 5, chewy: 4 },
  'sukiyaki': { umami: 8, richness: 7, spice: 1, sweet: 6 },
  'yakiniku': { umami: 8, richness: 6, spice: 2, bitter_char: 6 },
  'wagyu': { umami: 9, richness: 9, spice: 1, silky: 8 },
  'chashu': { umami: 8, richness: 8, spice: 1, sweet: 6, silky: 7 },
  'teriyaki': { umami: 7, richness: 5, spice: 1, sweet: 7, bitter_char: 4 },
  'chicken teriyaki': { umami: 7, richness: 5, spice: 1, sweet: 7 },
  'salmon teriyaki': { umami: 7, richness: 6, spice: 1, sweet: 6 },
  'onigiri': { umami: 5, richness: 2, spice: 1 },
  'tamago': { umami: 5, richness: 4, spice: 1, sweet: 5, silky: 7 },
  'ikura': { umami: 8, richness: 5, spice: 1, bright_acid: 3 },
  'uni': { umami: 9, richness: 7, spice: 1, bright_acid: 3, silky: 9 },
  'toro': { umami: 8, richness: 9, spice: 1, silky: 9 },
  'hamachi': { umami: 7, richness: 5, spice: 1, silky: 8 },

  // ── Italian ───────────────────────────────────────────────────────────────
  'carbonara': { umami: 8, richness: 9, spice: 1, chewy: 5, creamy: 7 },
  'spaghetti carbonara': { umami: 8, richness: 9, spice: 1, chewy: 6, creamy: 7 },
  'cacio e pepe': { umami: 7, richness: 7, spice: 4, chewy: 6, creamy: 5 },
  'amatriciana': { umami: 8, richness: 7, spice: 3, bright_acid: 5, chewy: 6 },
  'bolognese': { umami: 9, richness: 8, spice: 1, chewy: 5, sweet: 3 },
  'ragu': { umami: 8, richness: 8, spice: 1, chewy: 4 },
  'pesto pasta': { umami: 6, richness: 7, spice: 1, bitter_char: 4, chewy: 5 },
  'aglio e olio': { umami: 5, richness: 6, spice: 3, chewy: 5 },
  'puttanesca': { umami: 8, richness: 5, spice: 4, bright_acid: 6, chewy: 5 },
  'arrabiata': { umami: 6, richness: 4, spice: 7, bright_acid: 6, chewy: 5 },
  'vongole': { umami: 8, richness: 5, spice: 2, bright_acid: 5, chewy: 5 },
  'linguine alle vongole': { umami: 8, richness: 5, spice: 2, bright_acid: 5 },
  'lasagna': { umami: 8, richness: 8, spice: 1, chewy: 4, creamy: 5 },
  'lasagne': { umami: 8, richness: 8, spice: 1, chewy: 4, creamy: 5 },
  'fettuccine alfredo': { umami: 6, richness: 9, spice: 1, chewy: 5, creamy: 9 },
  'gnocchi': { umami: 5, richness: 5, spice: 1, chewy: 6 },
  'gnocchi al pesto': { umami: 6, richness: 7, spice: 1, chewy: 5 },
  'risotto': { umami: 7, richness: 7, spice: 1, creamy: 8, silky: 7 },
  'mushroom risotto': { umami: 9, richness: 7, spice: 1, creamy: 8 },
  'porcini risotto': { umami: 9, richness: 7, spice: 1, creamy: 8 },
  'truffle risotto': { umami: 9, richness: 8, spice: 1, creamy: 8 },
  'seafood risotto': { umami: 8, richness: 6, spice: 1, bright_acid: 3, creamy: 7 },
  'osso buco': { umami: 9, richness: 8, spice: 1, bright_acid: 4 },
  'bistecca fiorentina': { umami: 9, richness: 8, spice: 1, bitter_char: 7 },
  'saltimbocca': { umami: 8, richness: 6, spice: 1, bright_acid: 4 },
  'piccata': { umami: 6, richness: 6, spice: 1, bright_acid: 7 },
  'chicken piccata': { umami: 6, richness: 6, spice: 1, bright_acid: 7 },
  'parmigiana': { umami: 8, richness: 8, spice: 2, crispy: 5, creamy: 5 },
  'chicken parmigiana': { umami: 8, richness: 8, spice: 2, crispy: 6 },
  'eggplant parmigiana': { umami: 7, richness: 7, spice: 1, crispy: 5 },
  'margherita pizza': { umami: 7, richness: 5, spice: 1, bright_acid: 5, crispy: 5 },
  'pepperoni pizza': { umami: 8, richness: 7, spice: 4, crispy: 5 },
  'quattro formaggi': { umami: 7, richness: 9, spice: 1, crispy: 4, creamy: 7 },
  'pizza': { umami: 7, richness: 6, spice: 2, crispy: 5 },
  'calzone': { umami: 8, richness: 7, spice: 2, chewy: 5 },
  'focaccia': { umami: 4, richness: 5, spice: 1, crispy: 5 },
  'bruschetta': { umami: 5, richness: 4, spice: 1, bright_acid: 6, crispy: 6 },
  'caprese': { umami: 5, richness: 5, spice: 1, bright_acid: 5 },
  'prosciutto': { umami: 8, richness: 6, spice: 1, sweet: 3 },
  'antipasto': { umami: 7, richness: 5, spice: 2, bright_acid: 5 },
  'burrata': { umami: 5, richness: 8, spice: 1, creamy: 9, silky: 8 },
  'carpaccio': { umami: 7, richness: 4, spice: 2, bright_acid: 6 },
  'bresaola': { umami: 7, richness: 3, spice: 1, bright_acid: 4 },
  'arancini': { umami: 6, richness: 6, spice: 1, crispy: 7 },
  'tiramisu': { umami: 2, richness: 7, spice: 1, sweet: 8, bitter_char: 5, creamy: 7 },
  'panna cotta': { umami: 1, richness: 6, spice: 1, sweet: 7, creamy: 9, silky: 9 },

  // ── Mexican ───────────────────────────────────────────────────────────────
  'carne asada taco': { umami: 8, richness: 5, spice: 4, bright_acid: 6, bitter_char: 6 },
  'al pastor taco': { umami: 7, richness: 5, spice: 5, sweet: 6, bright_acid: 5 },
  'carnitas taco': { umami: 7, richness: 8, spice: 2, bright_acid: 4, crispy: 5 },
  'barbacoa taco': { umami: 8, richness: 8, spice: 4, bright_acid: 4 },
  'fish taco': { umami: 5, richness: 4, spice: 3, bright_acid: 7, crispy: 6 },
  'shrimp taco': { umami: 5, richness: 4, spice: 4, bright_acid: 7, crispy: 5 },
  'chorizo taco': { umami: 7, richness: 7, spice: 7, bitter_char: 4 },
  'birria taco': { umami: 9, richness: 8, spice: 5, bitter_char: 4, chewy: 5 },
  'birria': { umami: 9, richness: 8, spice: 5, bitter_char: 4 },
  'taco': { umami: 7, richness: 5, spice: 4, bright_acid: 5 },
  'burrito': { umami: 7, richness: 6, spice: 4, chewy: 4 },
  'enchilada': { umami: 7, richness: 7, spice: 5, chewy: 4 },
  'mole': { umami: 7, richness: 7, spice: 4, bitter_char: 6, sweet: 5 },
  'chicken mole': { umami: 8, richness: 7, spice: 4, bitter_char: 6, sweet: 5 },
  'mole negro': { umami: 7, richness: 7, spice: 5, bitter_char: 7, sweet: 4 },
  'pozole': { umami: 7, richness: 5, spice: 4, bright_acid: 3, chewy: 5 },
  'pozole rojo': { umami: 7, richness: 5, spice: 5, chewy: 5 },
  'tamale': { umami: 5, richness: 5, spice: 3, chewy: 5 },
  'tamales': { umami: 5, richness: 5, spice: 3, chewy: 5 },
  'chile relleno': { umami: 6, richness: 7, spice: 4, crispy: 5, creamy: 5 },
  'quesadilla': { umami: 5, richness: 7, spice: 2, crispy: 6, creamy: 5 },
  'nachos': { umami: 6, richness: 7, spice: 5, crispy: 8 },
  'guacamole': { umami: 3, richness: 7, spice: 2, bright_acid: 6, creamy: 8 },
  'ceviche': { umami: 6, richness: 2, spice: 5, bright_acid: 9 },
  'aguachile': { umami: 5, richness: 2, spice: 8, bright_acid: 9 },
  'elote': { umami: 4, richness: 6, spice: 3, sweet: 7, creamy: 5 },
  'huevos rancheros': { umami: 6, richness: 6, spice: 5, bright_acid: 5 },
  'chilaquiles': { umami: 6, richness: 6, spice: 5, bright_acid: 5, crispy: 5 },
  'fajitas': { umami: 7, richness: 5, spice: 4, bitter_char: 6 },
  'chiles en nogada': { umami: 6, richness: 7, spice: 3, sweet: 6 },

  // ── Thai ──────────────────────────────────────────────────────────────────
  'pad thai': { umami: 7, richness: 4, spice: 3, bright_acid: 5, sweet: 5, chewy: 5 },
  'green curry': { umami: 7, richness: 7, spice: 8, bright_acid: 4, creamy: 6 },
  'red curry': { umami: 7, richness: 7, spice: 7, bright_acid: 3, sweet: 4, creamy: 6 },
  'yellow curry': { umami: 6, richness: 6, spice: 4, sweet: 5, creamy: 6 },
  'massaman curry': { umami: 6, richness: 7, spice: 3, sweet: 6, creamy: 6 },
  'panang curry': { umami: 7, richness: 8, spice: 5, sweet: 5, creamy: 7 },
  'pad kra pao': { umami: 8, richness: 5, spice: 8, bright_acid: 3 },
  'pad see ew': { umami: 7, richness: 5, spice: 2, sweet: 5, bitter_char: 4, chewy: 5 },
  'drunken noodles': { umami: 7, richness: 5, spice: 7, bright_acid: 3, chewy: 5 },
  'pad kee mao': { umami: 7, richness: 5, spice: 7, bright_acid: 3, chewy: 5 },
  'tom yum': { umami: 7, richness: 3, spice: 7, bright_acid: 8 },
  'tom yum goong': { umami: 7, richness: 3, spice: 7, bright_acid: 8 },
  'tom kha gai': { umami: 6, richness: 7, spice: 4, bright_acid: 5, creamy: 6 },
  'som tum': { umami: 5, richness: 2, spice: 7, bright_acid: 8, sweet: 4 },
  'papaya salad': { umami: 5, richness: 2, spice: 7, bright_acid: 8, sweet: 4 },
  'larb': { umami: 7, richness: 4, spice: 7, bright_acid: 7, bitter_char: 4 },
  'laab': { umami: 7, richness: 4, spice: 7, bright_acid: 7 },
  'thai satay': { umami: 6, richness: 6, spice: 3, sweet: 5, bitter_char: 5 },
  'satay': { umami: 6, richness: 6, spice: 3, sweet: 5, bitter_char: 5 },
  'mango sticky rice': { umami: 1, richness: 5, spice: 1, sweet: 8, creamy: 6 },
  'pad woon sen': { umami: 6, richness: 4, spice: 3, chewy: 6 },
  'khao soi': { umami: 7, richness: 7, spice: 5, bright_acid: 4, creamy: 6, crispy: 4 },
  'boat noodles': { umami: 9, richness: 7, spice: 5, chewy: 5 },
  'basil fried rice': { umami: 7, richness: 4, spice: 6, bitter_char: 3 },
  'pineapple fried rice': { umami: 5, richness: 3, spice: 2, sweet: 6, bright_acid: 4 },

  // ── Indian ────────────────────────────────────────────────────────────────
  'butter chicken': { umami: 6, richness: 8, spice: 3, sweet: 5, creamy: 8 },
  'chicken tikka masala': { umami: 7, richness: 8, spice: 4, bright_acid: 4, creamy: 7 },
  'chicken tikka': { umami: 7, richness: 5, spice: 5, bitter_char: 6 },
  'saag paneer': { umami: 5, richness: 7, spice: 4, bitter_char: 4, creamy: 6 },
  'palak paneer': { umami: 5, richness: 7, spice: 4, bitter_char: 4, creamy: 6 },
  'paneer makhani': { umami: 6, richness: 8, spice: 3, sweet: 4, creamy: 8 },
  'chana masala': { umami: 6, richness: 4, spice: 5, bright_acid: 5 },
  'dal makhani': { umami: 7, richness: 8, spice: 3, creamy: 7 },
  'dal tadka': { umami: 6, richness: 5, spice: 5, bright_acid: 4 },
  'lamb rogan josh': { umami: 8, richness: 8, spice: 6, bitter_char: 4 },
  'lamb vindaloo': { umami: 7, richness: 7, spice: 9, bright_acid: 6 },
  'vindaloo': { umami: 7, richness: 6, spice: 9, bright_acid: 6 },
  'korma': { umami: 5, richness: 9, spice: 2, sweet: 5, creamy: 8 },
  'chicken korma': { umami: 5, richness: 9, spice: 2, sweet: 5, creamy: 8 },
  'biryani': { umami: 7, richness: 6, spice: 5, bitter_char: 3, sweet: 3 },
  'chicken biryani': { umami: 7, richness: 6, spice: 5 },
  'lamb biryani': { umami: 8, richness: 7, spice: 6 },
  'vegetable biryani': { umami: 5, richness: 5, spice: 4 },
  'tandoori chicken': { umami: 7, richness: 4, spice: 5, bitter_char: 7 },
  'naan': { umami: 3, richness: 3, spice: 1, bitter_char: 4 },
  'garlic naan': { umami: 4, richness: 4, spice: 1, bitter_char: 4 },
  'samosa': { umami: 4, richness: 4, spice: 5, crispy: 8 },
  'aloo gobi': { umami: 4, richness: 3, spice: 5 },
  'aloo tikki': { umami: 4, richness: 3, spice: 5, crispy: 7 },
  'chaat': { umami: 5, richness: 3, spice: 5, bright_acid: 7, sweet: 4, crispy: 5 },
  'pani puri': { umami: 4, richness: 2, spice: 6, bright_acid: 8, crispy: 7 },
  'bhel puri': { umami: 4, richness: 2, spice: 4, bright_acid: 6, sweet: 4, crispy: 6 },
  'chole bhature': { umami: 6, richness: 6, spice: 5, bright_acid: 4, crispy: 5 },
  'rajma': { umami: 6, richness: 5, spice: 4 },
  'malai kofta': { umami: 5, richness: 9, spice: 2, sweet: 4, creamy: 8 },
  'idli': { umami: 4, richness: 2, spice: 1 },
  'dosa': { umami: 4, richness: 3, spice: 2, crispy: 8 },
  'masala dosa': { umami: 5, richness: 4, spice: 4, crispy: 8 },
  'rava dosa': { umami: 4, richness: 3, spice: 2, crispy: 9 },
  'uttapam': { umami: 4, richness: 3, spice: 2 },
  'rasam': { umami: 5, richness: 2, spice: 6, bright_acid: 7 },
  'haleem': { umami: 8, richness: 7, spice: 6, silky: 6 },

  // ── French ────────────────────────────────────────────────────────────────
  'beef bourguignon': { umami: 9, richness: 8, spice: 1, bitter_char: 5, sweet: 3 },
  'coq au vin': { umami: 8, richness: 7, spice: 1, bitter_char: 5 },
  'duck confit': { umami: 8, richness: 9, spice: 1, bitter_char: 3, crispy: 6 },
  'cassoulet': { umami: 8, richness: 8, spice: 1, bitter_char: 3 },
  'bouillabaisse': { umami: 8, richness: 6, spice: 2, bright_acid: 4 },
  'sole meuniere': { umami: 6, richness: 7, spice: 1, bright_acid: 5 },
  'steak frites': { umami: 8, richness: 7, spice: 1, bitter_char: 6, crispy: 7 },
  'steak tartare': { umami: 8, richness: 5, spice: 3, bright_acid: 4 },
  'croque monsieur': { umami: 7, richness: 8, spice: 1, crispy: 6, creamy: 5 },
  'croque madame': { umami: 7, richness: 8, spice: 1, crispy: 6, creamy: 5, silky: 5 },
  'onion soup': { umami: 8, richness: 6, spice: 1, sweet: 5, bitter_char: 4 },
  'french onion soup': { umami: 8, richness: 6, spice: 1, sweet: 5, bitter_char: 4 },
  'escargot': { umami: 7, richness: 7, spice: 2, bitter_char: 4 },
  'foie gras': { umami: 8, richness: 10, spice: 1, sweet: 3, silky: 9 },
  'pate': { umami: 8, richness: 8, spice: 2, bitter_char: 3 },
  'terrine': { umami: 7, richness: 7, spice: 1, bitter_char: 3 },
  'ratatouille': { umami: 5, richness: 4, spice: 1, bright_acid: 5 },
  'quiche lorraine': { umami: 7, richness: 8, spice: 1, crispy: 4, creamy: 6 },
  'croissant': { umami: 2, richness: 7, spice: 1, crispy: 6, sweet: 3 },
  'crepe': { umami: 2, richness: 5, spice: 1, sweet: 5 },
  'boeuf tartare': { umami: 8, richness: 5, spice: 3, bright_acid: 4 },
  'chateaubriand': { umami: 9, richness: 8, spice: 1, bitter_char: 5 },
  'blanquette de veau': { umami: 7, richness: 8, spice: 1, creamy: 7 },
  'pot au feu': { umami: 8, richness: 6, spice: 1 },

  // ── Chinese ───────────────────────────────────────────────────────────────
  'kung pao chicken': { umami: 7, richness: 5, spice: 7, sweet: 5, bitter_char: 4, crispy: 4 },
  'mapo tofu': { umami: 8, richness: 6, spice: 9, silky: 7 },
  'dan dan noodles': { umami: 8, richness: 7, spice: 7, chewy: 5 },
  'sichuan hot pot': { umami: 9, richness: 8, spice: 9, bright_acid: 2 },
  'hot pot': { umami: 9, richness: 7, spice: 7 },
  'peking duck': { umami: 8, richness: 7, spice: 1, sweet: 5, crispy: 9, bitter_char: 3 },
  'general tso chicken': { umami: 6, richness: 6, spice: 5, sweet: 6, crispy: 7 },
  'sweet and sour pork': { umami: 5, richness: 5, spice: 1, bright_acid: 5, sweet: 7, crispy: 6 },
  'char siu': { umami: 8, richness: 7, spice: 1, sweet: 7, bitter_char: 5 },
  'dim sum': { umami: 6, richness: 5, spice: 2, chewy: 5 },
  'har gow': { umami: 6, richness: 3, spice: 1, chewy: 6, silky: 5 },
  'siu mai': { umami: 7, richness: 5, spice: 2, chewy: 5 },
  'xiao long bao': { umami: 8, richness: 7, spice: 1, chewy: 5, silky: 5 },
  'soup dumplings': { umami: 8, richness: 7, spice: 1, chewy: 5, silky: 5 },
  'char siu bao': { umami: 7, richness: 6, spice: 1, sweet: 6 },
  'lo mein': { umami: 6, richness: 4, spice: 2, sweet: 4, chewy: 5 },
  'chow mein': { umami: 6, richness: 4, spice: 2, crispy: 5, chewy: 4 },
  'beef chow fun': { umami: 7, richness: 5, spice: 2, bitter_char: 5, chewy: 6 },
  'fried rice': { umami: 6, richness: 4, spice: 2, bitter_char: 3 },
  'yang chow fried rice': { umami: 6, richness: 4, spice: 1, bitter_char: 3 },
  'congee': { umami: 5, richness: 4, spice: 1, silky: 8 },
  'hot and sour soup': { umami: 7, richness: 4, spice: 5, bright_acid: 7, silky: 5 },
  'wonton soup': { umami: 7, richness: 4, spice: 1, chewy: 5 },
  'egg drop soup': { umami: 6, richness: 4, spice: 1, silky: 7 },
  'scallion pancake': { umami: 4, richness: 5, spice: 1, crispy: 7 },
  'red braised pork belly': { umami: 8, richness: 9, spice: 1, sweet: 6, silky: 7 },
  'twice cooked pork': { umami: 7, richness: 7, spice: 6, bitter_char: 4 },
  'salt and pepper squid': { umami: 6, richness: 4, spice: 4, crispy: 9 },
  'black bean sauce': { umami: 8, richness: 5, spice: 2, bitter_char: 5 },
  'mongolian beef': { umami: 7, richness: 5, spice: 2, sweet: 6 },
  'orange chicken': { umami: 5, richness: 5, spice: 2, sweet: 7, bright_acid: 4, crispy: 7 },
  'ma po doufu': { umami: 8, richness: 6, spice: 9, silky: 7 },
  'hong shao rou': { umami: 8, richness: 9, spice: 1, sweet: 6, silky: 7 },

  // ── Korean ────────────────────────────────────────────────────────────────
  'bibimbap': { umami: 7, richness: 5, spice: 5, bright_acid: 4, bitter_char: 4 },
  'dolsot bibimbap': { umami: 7, richness: 5, spice: 5, bright_acid: 4, crispy: 6 },
  'japchae': { umami: 6, richness: 4, spice: 2, sweet: 5, chewy: 7 },
  'bulgogi': { umami: 7, richness: 5, spice: 2, sweet: 6, bitter_char: 5 },
  'galbi': { umami: 8, richness: 6, spice: 2, sweet: 6, bitter_char: 6 },
  'galbi jjim': { umami: 8, richness: 7, spice: 2, sweet: 6 },
  'samgyeopsal': { umami: 7, richness: 8, spice: 2, bitter_char: 6 },
  'korean bbq': { umami: 8, richness: 6, spice: 3, bitter_char: 6, sweet: 5 },
  'kimchi jjigae': { umami: 8, richness: 6, spice: 7, bright_acid: 6 },
  'doenjang jjigae': { umami: 9, richness: 5, spice: 3 },
  'sundubu jjigae': { umami: 8, richness: 6, spice: 7, silky: 6 },
  'tteokbokki': { umami: 6, richness: 4, spice: 7, sweet: 5, chewy: 8 },
  'kimchi': { umami: 7, richness: 2, spice: 6, bright_acid: 7 },
  'kimchi fried rice': { umami: 8, richness: 5, spice: 6, bright_acid: 4 },
  'dakgalbi': { umami: 7, richness: 5, spice: 7, sweet: 5 },
  'naengmyeon': { umami: 5, richness: 2, spice: 3, bright_acid: 7 },
  'bibim naengmyeon': { umami: 6, richness: 3, spice: 6, bright_acid: 6 },
  'gamjatang': { umami: 8, richness: 6, spice: 7 },
  'seolleongtang': { umami: 7, richness: 5, spice: 1, silky: 6 },
  'gomtang': { umami: 8, richness: 6, spice: 1, silky: 7 },
  'haemul pajeon': { umami: 7, richness: 4, spice: 2, crispy: 7, chewy: 5 },
  'korean fried chicken': { umami: 7, richness: 6, spice: 5, sweet: 5, crispy: 9 },
  'dakdoritang': { umami: 7, richness: 5, spice: 6, sweet: 4 },

  // ── Mediterranean / Middle Eastern ────────────────────────────────────────
  'hummus': { umami: 4, richness: 6, spice: 2, bright_acid: 4, creamy: 7 },
  'falafel': { umami: 4, richness: 3, spice: 3, bitter_char: 4, crispy: 8 },
  'shawarma': { umami: 7, richness: 6, spice: 4, bitter_acid: 4 },
  'chicken shawarma': { umami: 7, richness: 5, spice: 4, bright_acid: 4, bitter_char: 4 },
  'kebab': { umami: 7, richness: 5, spice: 4, bitter_char: 5 },
  'lamb kebab': { umami: 7, richness: 6, spice: 4, bitter_char: 5 },
  'kofta': { umami: 7, richness: 6, spice: 5, bitter_char: 5 },
  'baba ganoush': { umami: 5, richness: 5, spice: 2, bright_acid: 4, bitter_char: 5, creamy: 7 },
  'tabbouleh': { umami: 3, richness: 3, spice: 1, bright_acid: 7 },
  'fattoush': { umami: 3, richness: 3, spice: 2, bright_acid: 7, crispy: 5 },
  'moussaka': { umami: 7, richness: 8, spice: 3, creamy: 5 },
  'spanakopita': { umami: 5, richness: 6, spice: 1, bitter_char: 3, crispy: 7 },
  'dolma': { umami: 5, richness: 4, spice: 2, bright_acid: 4 },
  'dolmades': { umami: 5, richness: 4, spice: 2, bright_acid: 4 },
  'baklava': { umami: 1, richness: 7, spice: 1, sweet: 9, crispy: 5 },
  'tzatziki': { umami: 2, richness: 5, spice: 1, bright_acid: 5, creamy: 7 },
  'pita': { umami: 3, richness: 2, spice: 1, crispy: 3 },
  'gyros': { umami: 7, richness: 6, spice: 3, bright_acid: 4 },
  'souvlaki': { umami: 7, richness: 5, spice: 2, bitter_char: 5 },
  'greek salad': { umami: 4, richness: 5, spice: 1, bright_acid: 6 },
  'harissa': { umami: 5, richness: 4, spice: 9, bitter_char: 5 },
  'shakshuka': { umami: 6, richness: 5, spice: 5, bright_acid: 6 },
  'tagine': { umami: 6, richness: 6, spice: 4, sweet: 5 },
  'lamb tagine': { umami: 7, richness: 6, spice: 4, sweet: 5 },
  'couscous': { umami: 3, richness: 3, spice: 2, sweet: 3 },
  'persian rice': { umami: 3, richness: 4, spice: 2, bitter_char: 4, crispy: 6 },
  'mansaf': { umami: 7, richness: 7, spice: 2, bright_acid: 4 },
  'mujaddara': { umami: 6, richness: 4, spice: 2, bitter_char: 4 },
  'ful medames': { umami: 5, richness: 4, spice: 3, bright_acid: 5 },

  // ── American / Steakhouse / BBQ ───────────────────────────────────────────
  'ribeye': { umami: 9, richness: 9, spice: 1, bitter_char: 6 },
  'new york strip': { umami: 8, richness: 7, spice: 1, bitter_char: 6 },
  'filet mignon': { umami: 8, richness: 7, spice: 1, bitter_char: 4, silky: 7 },
  'tomahawk': { umami: 9, richness: 9, spice: 1, bitter_char: 7 },
  'wagyu steak': { umami: 9, richness: 10, spice: 1, silky: 9 },
  'porterhouse': { umami: 9, richness: 8, spice: 1, bitter_char: 6 },
  'prime rib': { umami: 9, richness: 9, spice: 1 },
  'brisket': { umami: 9, richness: 8, spice: 2, bitter_char: 7 },
  'smoked brisket': { umami: 9, richness: 8, spice: 2, bitter_char: 8 },
  'pulled pork': { umami: 8, richness: 7, spice: 3, sweet: 6, bitter_char: 5 },
  'smoked ribs': { umami: 8, richness: 7, spice: 3, sweet: 5, bitter_char: 7 },
  'baby back ribs': { umami: 7, richness: 7, spice: 3, sweet: 5, bitter_char: 6 },
  'st louis ribs': { umami: 8, richness: 7, spice: 3, sweet: 5, bitter_char: 7 },
  'burnt ends': { umami: 9, richness: 8, spice: 2, bitter_char: 9 },
  'burger': { umami: 7, richness: 7, spice: 2, bitter_char: 5 },
  'smash burger': { umami: 8, richness: 8, spice: 2, bitter_char: 6, crispy: 6 },
  'cheeseburger': { umami: 8, richness: 8, spice: 2, bitter_char: 5 },
  'bacon cheeseburger': { umami: 8, richness: 9, spice: 2, bitter_char: 6 },
  'hot dog': { umami: 5, richness: 5, spice: 2, chewy: 4 },
  'fried chicken': { umami: 6, richness: 6, spice: 3, crispy: 9 },
  'nashville hot chicken': { umami: 6, richness: 6, spice: 9, crispy: 9 },
  'buffalo wings': { umami: 6, richness: 5, spice: 7, bright_acid: 5, crispy: 7 },
  'chicken wings': { umami: 6, richness: 5, spice: 3, crispy: 8 },
  'mac and cheese': { umami: 6, richness: 9, spice: 1, creamy: 9, crispy: 3 },
  'lobster mac': { umami: 8, richness: 9, spice: 1, creamy: 9 },
  'clam chowder': { umami: 7, richness: 8, spice: 1, creamy: 8 },
  'lobster bisque': { umami: 8, richness: 8, spice: 1, creamy: 9, silky: 7 },
  'crab cakes': { umami: 7, richness: 5, spice: 3, crispy: 7 },
  'lobster roll': { umami: 7, richness: 6, spice: 1, creamy: 5 },
  'po boy': { umami: 6, richness: 5, spice: 3, crispy: 7 },
  'gumbo': { umami: 8, richness: 7, spice: 5, chewy: 4 },
  'jambalaya': { umami: 7, richness: 6, spice: 6 },
  'caesar salad': { umami: 6, richness: 5, spice: 2, bright_acid: 5, bitter_char: 3 },
  'club sandwich': { umami: 6, richness: 5, spice: 1, crispy: 4 },
  'reuben': { umami: 7, richness: 7, spice: 2, bright_acid: 5 },
  'philly cheesesteak': { umami: 7, richness: 7, spice: 2, chewy: 5, creamy: 5 },

  // ── Vietnamese ────────────────────────────────────────────────────────────
  'pho bo': { umami: 8, richness: 5, spice: 2, bright_acid: 5, chewy: 4 },
  'pho ga': { umami: 7, richness: 4, spice: 1, bright_acid: 4 },
  'pho': { umami: 8, richness: 5, spice: 2, bright_acid: 5 },
  'banh mi': { umami: 7, richness: 5, spice: 4, bright_acid: 7, crispy: 7 },
  'bun bo hue': { umami: 8, richness: 6, spice: 7, bright_acid: 4 },
  'bun rieu': { umami: 7, richness: 5, spice: 4, bright_acid: 7 },
  'bun cha': { umami: 7, richness: 5, spice: 3, bright_acid: 6, sweet: 4 },
  'com tam': { umami: 7, richness: 5, spice: 2, bitter_char: 5 },
  'com suon': { umami: 7, richness: 5, spice: 2, bitter_char: 5 },
  'goi cuon': { umami: 4, richness: 2, spice: 2, bright_acid: 5 },
  'fresh spring rolls': { umami: 4, richness: 2, spice: 2, bright_acid: 5 },
  'cha gio': { umami: 5, richness: 4, spice: 2, crispy: 9 },
  'vietnamese spring rolls': { umami: 5, richness: 4, spice: 2, crispy: 8 },
  'ca kho to': { umami: 8, richness: 6, spice: 2, sweet: 5, bitter_char: 4 },
  'thit kho': { umami: 7, richness: 7, spice: 2, sweet: 5 },
  'banh xeo': { umami: 5, richness: 4, spice: 3, crispy: 9, bright_acid: 5 },
  'mi quang': { umami: 7, richness: 5, spice: 4, bright_acid: 5 },

  // ── Spanish ───────────────────────────────────────────────────────────────
  'paella': { umami: 8, richness: 5, spice: 3, bitter_char: 5, crispy: 4 },
  'paella valenciana': { umami: 7, richness: 5, spice: 3, bitter_char: 5 },
  'seafood paella': { umami: 8, richness: 5, spice: 2, bitter_char: 5 },
  'jamon iberico': { umami: 9, richness: 7, spice: 1, sweet: 3 },
  'patatas bravas': { umami: 3, richness: 4, spice: 7, bright_acid: 5, crispy: 8 },
  'tortilla espanola': { umami: 5, richness: 6, spice: 1, silky: 5 },
  'gambas al ajillo': { umami: 7, richness: 7, spice: 4, bright_acid: 3 },
  'croquetas': { umami: 5, richness: 7, spice: 1, crispy: 8, creamy: 7 },
  'gazpacho': { umami: 4, richness: 2, spice: 2, bright_acid: 7 },
  'salmorejo': { umami: 4, richness: 4, spice: 1, bright_acid: 6, creamy: 5 },
  'pulpo a la gallega': { umami: 7, richness: 4, spice: 4, chewy: 6 },
  'chorizo': { umami: 7, richness: 7, spice: 6, bitter_char: 4 },
  'pisto': { umami: 5, richness: 4, spice: 2, bright_acid: 5 },
  'albondigas': { umami: 7, richness: 6, spice: 3, bright_acid: 4 },
  'cochinillo': { umami: 7, richness: 8, spice: 1, crispy: 9 },

  // ── Ethiopian ─────────────────────────────────────────────────────────────
  'injera': { umami: 3, richness: 2, spice: 1, bright_acid: 7, chewy: 4 },
  'doro wat': { umami: 7, richness: 6, spice: 8, bitter_char: 3 },
  'tibs': { umami: 7, richness: 5, spice: 5, bitter_char: 5 },
  'misir wot': { umami: 5, richness: 4, spice: 7 },
  'shiro': { umami: 5, richness: 4, spice: 5, creamy: 5 },
  'kitfo': { umami: 7, richness: 7, spice: 4 },
  'gored gored': { umami: 8, richness: 6, spice: 5 },
  'ayib': { umami: 2, richness: 5, spice: 1, bright_acid: 4 },
  'yetsom beyaynetu': { umami: 4, richness: 3, spice: 5 },
  'lentil stew': { umami: 5, richness: 3, spice: 4 },

  // ── Peruvian ──────────────────────────────────────────────────────────────
  'ceviche peruano': { umami: 6, richness: 3, spice: 7, bright_acid: 9 },
  'lomo saltado': { umami: 8, richness: 6, spice: 4, bright_acid: 5, bitter_char: 5 },
  'aji de gallina': { umami: 7, richness: 8, spice: 3, creamy: 7 },
  'causa rellena': { umami: 5, richness: 5, spice: 3, creamy: 6 },
  'anticucho': { umami: 7, richness: 5, spice: 5, bitter_char: 6 },
  'papa a la huancaina': { umami: 4, richness: 7, spice: 4, creamy: 7 },
  'tiradito': { umami: 6, richness: 3, spice: 5, bright_acid: 8 },
  'seco de cordero': { umami: 7, richness: 7, spice: 4, bright_acid: 4 },
  'arroz con leche': { umami: 1, richness: 6, spice: 1, sweet: 8, creamy: 7 },

  // ── Brazilian ─────────────────────────────────────────────────────────────
  'feijoada': { umami: 8, richness: 8, spice: 2, bitter_char: 3 },
  'churrasco': { umami: 8, richness: 7, spice: 1, bitter_char: 7 },
  'picanha': { umami: 9, richness: 7, spice: 1, bitter_char: 6 },
  'pao de queijo': { umami: 4, richness: 5, spice: 1, chewy: 6 },
  'moqueca': { umami: 7, richness: 7, spice: 4, creamy: 6 },
  'vatapa': { umami: 6, richness: 8, spice: 4, creamy: 6 },
  'brigadeiro': { umami: 1, richness: 7, spice: 1, sweet: 9, creamy: 7 },
  'coxinha': { umami: 5, richness: 6, spice: 2, crispy: 8, creamy: 5 },

  // ── Greek ─────────────────────────────────────────────────────────────────
  'lamb chops': { umami: 8, richness: 7, spice: 2, bitter_char: 6 },
  'pastitsio': { umami: 7, richness: 7, spice: 2, creamy: 5 },
  'horiatiki': { umami: 4, richness: 5, spice: 1, bright_acid: 6 },
  'loukoumades': { umami: 1, richness: 5, spice: 1, sweet: 8, crispy: 5 },
  'saganaki': { umami: 5, richness: 7, spice: 1, bright_acid: 4, crispy: 7 },
  'keftedes': { umami: 7, richness: 5, spice: 3, bitter_char: 4 },
  'fasolada': { umami: 5, richness: 4, spice: 1, bright_acid: 3 },
  'avgolemono': { umami: 5, richness: 5, spice: 1, bright_acid: 6, silky: 7 },

  // ── Seafood ───────────────────────────────────────────────────────────────
  'grilled salmon': { umami: 7, richness: 6, spice: 1, bitter_char: 5 },
  'pan seared salmon': { umami: 7, richness: 6, spice: 1, bitter_char: 4, crispy: 5 },
  'blackened salmon': { umami: 7, richness: 6, spice: 6, bitter_char: 7 },
  'grilled tuna': { umami: 7, richness: 5, spice: 1, bitter_char: 5 },
  'tuna steak': { umami: 7, richness: 5, spice: 1, bitter_char: 4 },
  'sea bass': { umami: 6, richness: 5, spice: 1, silky: 6 },
  'branzino': { umami: 6, richness: 4, spice: 1, bright_acid: 4, crispy: 4 },
  'halibut': { umami: 6, richness: 4, spice: 1, silky: 5 },
  'scallops': { umami: 7, richness: 4, spice: 1, sweet: 5, bitter_char: 5 },
  'pan seared scallops': { umami: 7, richness: 5, spice: 1, sweet: 5, bitter_char: 6, crispy: 5 },
  'oysters': { umami: 7, richness: 4, spice: 1, bright_acid: 4, silky: 7 },
  'oysters rockefeller': { umami: 7, richness: 8, spice: 2, bitter_char: 3 },
  'clams': { umami: 7, richness: 3, spice: 1, bright_acid: 4, chewy: 5 },
  'mussels': { umami: 7, richness: 4, spice: 2, bright_acid: 4, chewy: 5 },
  'moules mariniere': { umami: 7, richness: 5, spice: 2, bright_acid: 5 },
  'shrimp scampi': { umami: 6, richness: 7, spice: 2, bright_acid: 4 },
  'grilled shrimp': { umami: 6, richness: 3, spice: 2, bitter_char: 5 },
  'lobster': { umami: 7, richness: 5, spice: 1, sweet: 4, silky: 5 },
  'lobster thermidor': { umami: 8, richness: 9, spice: 1, creamy: 8 },
  'fish and chips': { umami: 5, richness: 5, spice: 1, crispy: 8 },
  'fish tacos': { umami: 5, richness: 4, spice: 4, bright_acid: 7, crispy: 6 },
  'crab': { umami: 7, richness: 4, spice: 1, sweet: 4 },
  'dungeness crab': { umami: 7, richness: 4, spice: 1, sweet: 5 },
  'king crab': { umami: 7, richness: 5, spice: 1, sweet: 5 },
  'steamed crab': { umami: 7, richness: 4, spice: 1, sweet: 4 },

  // ── Fusion / Modern ───────────────────────────────────────────────────────
  'truffle fries': { umami: 8, richness: 6, spice: 1, bitter_char: 3, crispy: 8 },
  'avocado toast': { umami: 3, richness: 7, spice: 2, bright_acid: 4, creamy: 6, crispy: 4 },
  'acai bowl': { umami: 1, richness: 4, spice: 1, sweet: 7, bright_acid: 5 },
  'grain bowl': { umami: 4, richness: 4, spice: 2, bright_acid: 5 },
  'poke bowl': { umami: 7, richness: 4, spice: 2, bright_acid: 5 },
  'ramen burger': { umami: 8, richness: 7, spice: 2, chewy: 6 },
  'korean fried chicken sandwich': { umami: 7, richness: 6, spice: 6, sweet: 4, crispy: 9 },
  'lobster tacos': { umami: 7, richness: 6, spice: 3, bright_acid: 5 },
  'duck tacos': { umami: 8, richness: 7, spice: 2, bitter_char: 4, crispy: 5 },
  'miso glazed cod': { umami: 9, richness: 6, spice: 1, sweet: 6, bitter_char: 4 },
  'miso black cod': { umami: 9, richness: 6, spice: 1, sweet: 7 },
  'short rib': { umami: 9, richness: 9, spice: 1, bitter_char: 4, silky: 7 },
  'braised short rib': { umami: 9, richness: 9, spice: 1, silky: 7 },
  'wagyu burger': { umami: 9, richness: 9, spice: 1, bitter_char: 5 },
  'foie gras torchon': { umami: 8, richness: 10, spice: 1, sweet: 4, silky: 9 },

  // ── Vegetarian / Vegan ────────────────────────────────────────────────────
  'mushroom risotto': { umami: 9, richness: 7, spice: 1, creamy: 8 },
  'roasted vegetables': { umami: 4, richness: 3, spice: 2, bitter_char: 5, sweet: 4 },
  'cauliflower steak': { umami: 4, richness: 4, spice: 2, bitter_char: 5 },
  'lentil soup': { umami: 5, richness: 3, spice: 3, bright_acid: 3 },
  'black bean burger': { umami: 6, richness: 4, spice: 3, bitter_char: 4 },
  'portobello mushroom': { umami: 8, richness: 4, spice: 1, bitter_char: 5 },
  'eggplant': { umami: 5, richness: 3, spice: 1, bitter_char: 5 },
  'tofu stir fry': { umami: 6, richness: 4, spice: 3, silky: 5 },
  'tempeh': { umami: 6, richness: 4, spice: 2, bitter_char: 4 },
  'jackfruit': { umami: 3, richness: 2, spice: 2, chewy: 6, sweet: 4 },
  'impossible burger': { umami: 7, richness: 6, spice: 1, bitter_char: 4 },
  'veggie burger': { umami: 5, richness: 4, spice: 2 },
  'stuffed peppers': { umami: 5, richness: 5, spice: 3, sweet: 5 },
  'shakshuka eggs': { umami: 6, richness: 5, spice: 5, bright_acid: 6 },
}

// ─── CUISINE SIGNALS ─────────────────────────────────────────────────────────
// Additive nudges applied when a restaurant's cuisine type is known.
// These represent the characteristic flavor fingerprint of each cuisine.

export const CUISINE_SIGNALS: Record<string, Partial<Record<FlavorAxis, number>>> = {
  japanese: {
    umami: 2.5,
    richness: 0,
    spice: -1,
    bright_acid: 0.5,
    sweet: 0,
    crispy: 0.5,
    silky: 1,
  },
  italian: {
    umami: 1.5,
    richness: 1.5,
    spice: 0,
    bright_acid: 0.5,
    chewy: 0.5,
    creamy: 0.5,
  },
  mexican: {
    spice: 1.5,
    bright_acid: 1.5,
    umami: 0.5,
    crispy: 0.5,
  },
  thai: {
    spice: 2,
    bright_acid: 2,
    umami: 1.5,
    sweet: 0.5,
    creamy: 0.5,
  },
  indian: {
    spice: 2,
    umami: 1,
    richness: 1,
    bitter_char: 0.5,
    creamy: 0.5,
  },
  french: {
    richness: 2.5,
    umami: 1.5,
    bitter_char: 0.5,
    bright_acid: 0.5,
    creamy: 1,
  },
  chinese: {
    umami: 1.5,
    sweet: 0.5,
    spice: 0.5,
    bright_acid: 0.5,
  },
  korean: {
    umami: 2,
    spice: 2,
    bright_acid: 1.5,
    sweet: 0.5,
    bitter_char: 0.5,
  },
  mediterranean: {
    bright_acid: 1.5,
    umami: 0.5,
    richness: 0.5,
    spice: 0.5,
  },
  middle_eastern: {
    spice: 1.5,
    bright_acid: 1,
    umami: 0.5,
    sweet: 0.5,
  },
  vietnamese: {
    bright_acid: 2,
    umami: 1.5,
    spice: 1,
    sweet: 0.5,
  },
  spanish: {
    umami: 1.5,
    spice: 0.5,
    bright_acid: 0.5,
    bitter_char: 0.5,
  },
  ethiopian: {
    spice: 2,
    umami: 1,
    bright_acid: 1.5,
    bitter_char: 0.5,
  },
  peruvian: {
    spice: 1.5,
    bright_acid: 2,
    umami: 1,
    richness: 0.5,
  },
  greek: {
    bright_acid: 1.5,
    umami: 0.5,
    richness: 0.5,
    bitter_char: 0.5,
  },
  american: {
    umami: 1,
    richness: 1.5,
    sweet: 0.5,
    bitter_char: 0.5,
  },
  brazilian: {
    umami: 1.5,
    richness: 1,
    bitter_char: 1,
    sweet: 0.5,
  },
  steakhouse: {
    umami: 2,
    richness: 2,
    bitter_char: 1,
    spice: 0,
  },
  seafood: {
    umami: 1.5,
    richness: 0.5,
    bright_acid: 0.5,
    sweet: 0.5,
  },
  sushi: {
    umami: 2.5,
    richness: 0,
    spice: -0.5,
    bright_acid: 0.5,
    silky: 1.5,
  },
}

// ─── KEYWORD SIGNALS ─────────────────────────────────────────────────────────
// Applied to item.name + description text (case-insensitive match).
// Each hit nudges the matched axes by `nudge` points (positive or negative).

export interface KeywordSignal {
  axes: FlavorAxis[]
  nudge: number
}

export const KEYWORD_SIGNALS: Record<string, KeywordSignal> = {
  // ── Umami ──────────────────────────────────────────────────────────────
  miso:         { axes: ['umami'], nudge: 2.5 },
  soy:          { axes: ['umami'], nudge: 1.5 },
  'soy sauce':  { axes: ['umami'], nudge: 2 },
  dashi:        { axes: ['umami'], nudge: 2.5 },
  bonito:       { axes: ['umami'], nudge: 2.5 },
  katsuobushi:  { axes: ['umami'], nudge: 2.5 },
  kombu:        { axes: ['umami'], nudge: 2 },
  umami:        { axes: ['umami'], nudge: 3 },
  anchovies:    { axes: ['umami'], nudge: 2.5 },
  anchovy:      { axes: ['umami'], nudge: 2.5 },
  worcestershire: { axes: ['umami'], nudge: 2 },
  parmesan:     { axes: ['umami', 'richness'], nudge: 1.5 },
  pecorino:     { axes: ['umami', 'richness'], nudge: 1.5 },
  mushroom:     { axes: ['umami'], nudge: 1.5 },
  truffle:      { axes: ['umami', 'richness'], nudge: 2 },
  porcini:      { axes: ['umami'], nudge: 2 },
  shiitake:     { axes: ['umami'], nudge: 2 },
  oyster:       { axes: ['umami'], nudge: 1.5 },
  maitake:      { axes: ['umami'], nudge: 2 },
  fermented:    { axes: ['umami', 'bright_acid'], nudge: 1.5 },
  'fish sauce': { axes: ['umami'], nudge: 2.5 },
  'nam pla':    { axes: ['umami', 'bright_acid'], nudge: 2 },
  'nam prik':   { axes: ['umami', 'spice'], nudge: 1.5 },
  kimchi:       { axes: ['umami', 'bright_acid', 'spice'], nudge: 1.5 },
  doenjang:     { axes: ['umami'], nudge: 2.5 },
  gochujang:    { axes: ['umami', 'spice', 'sweet'], nudge: 1.5 },
  bonito_flake: { axes: ['umami'], nudge: 2.5 },
  prosciutto:   { axes: ['umami', 'richness'], nudge: 1.5 },
  guanciale:    { axes: ['umami', 'richness'], nudge: 2 },
  pancetta:     { axes: ['umami', 'richness'], nudge: 1.5 },
  nduja:        { axes: ['umami', 'richness', 'spice'], nudge: 2 },
  bottarga:     { axes: ['umami'], nudge: 2 },
  colatura:     { axes: ['umami'], nudge: 2.5 },
  tamarind:     { axes: ['umami', 'bright_acid', 'sweet'], nudge: 1.5 },
  shrimp_paste: { axes: ['umami'], nudge: 2.5 },
  'oyster sauce': { axes: ['umami', 'sweet'], nudge: 1.5 },

  // ── Richness ────────────────────────────────────────────────────────────
  butter:       { axes: ['richness', 'creamy'], nudge: 2 },
  cream:        { axes: ['richness', 'creamy'], nudge: 2 },
  beurre:       { axes: ['richness', 'creamy'], nudge: 2.5 },
  foie:         { axes: ['richness', 'umami'], nudge: 3 },
  lard:         { axes: ['richness'], nudge: 2 },
  'duck fat':   { axes: ['richness'], nudge: 2.5 },
  tallow:       { axes: ['richness'], nudge: 2 },
  suet:         { axes: ['richness'], nudge: 2 },
  marrow:       { axes: ['richness', 'umami'], nudge: 2.5 },
  coconut:      { axes: ['richness', 'creamy', 'sweet'], nudge: 1.5 },
  avocado:      { axes: ['richness', 'creamy'], nudge: 1.5 },
  egg_yolk:     { axes: ['richness', 'silky'], nudge: 1.5 },
  hollandaise:  { axes: ['richness', 'creamy', 'bright_acid'], nudge: 2 },
  bearnaise:    { axes: ['richness', 'creamy', 'bright_acid'], nudge: 2 },
  alfredo:      { axes: ['richness', 'creamy'], nudge: 2.5 },
  'bone marrow': { axes: ['richness', 'umami'], nudge: 2.5 },
  wagyu:        { axes: ['richness', 'umami', 'silky'], nudge: 2.5 },
  ribeye:       { axes: ['richness', 'umami'], nudge: 2 },
  fatty:        { axes: ['richness'], nudge: 1.5 },
  braised:      { axes: ['richness', 'umami', 'silky'], nudge: 1.5 },
  confit:       { axes: ['richness', 'silky'], nudge: 2 },
  poached:      { axes: ['silky'], nudge: 1.5 },

  // ── Spice ───────────────────────────────────────────────────────────────
  spicy:        { axes: ['spice'], nudge: 2.5 },
  spice:        { axes: ['spice'], nudge: 1.5 },
  chili:        { axes: ['spice'], nudge: 2 },
  'chili oil':  { axes: ['spice', 'umami'], nudge: 2 },
  sriracha:     { axes: ['spice'], nudge: 2 },
  jalapeno:     { axes: ['spice'], nudge: 1.5 },
  habanero:     { axes: ['spice'], nudge: 3 },
  serrano:      { axes: ['spice'], nudge: 2 },
  cayenne:      { axes: ['spice'], nudge: 2.5 },
  pepper:       { axes: ['spice'], nudge: 1 },
  pepperoni:    { axes: ['spice', 'umami'], nudge: 1.5 },
  harissa:      { axes: ['spice', 'bright_acid'], nudge: 2 },
  wasabi:       { axes: ['spice'], nudge: 2.5 },
  horseradish:  { axes: ['spice', 'bright_acid'], nudge: 2 },
  sichuan:      { axes: ['spice', 'umami'], nudge: 2.5 },
  'szechuan':   { axes: ['spice', 'umami'], nudge: 2.5 },
  'mala':       { axes: ['spice', 'umami'], nudge: 2.5 },
  gochujang:    { axes: ['spice', 'sweet', 'umami'], nudge: 1.5 },
  chipotle:     { axes: ['spice', 'bitter_char'], nudge: 1.5 },
  adobo_chile:  { axes: ['spice', 'bitter_char'], nudge: 1.5 },
  ghost_pepper: { axes: ['spice'], nudge: 4 },
  thai_bird_chile: { axes: ['spice'], nudge: 3 },
  kung_pao:     { axes: ['spice', 'umami', 'sweet'], nudge: 1.5 },
  arrabbiata:   { axes: ['spice', 'bright_acid'], nudge: 2 },
  diavola:      { axes: ['spice'], nudge: 2 },
  'nashville hot': { axes: ['spice'], nudge: 3.5 },

  // ── Bitter / Char ────────────────────────────────────────────────────────
  grilled:      { axes: ['bitter_char'], nudge: 1.5 },
  charred:      { axes: ['bitter_char'], nudge: 2.5 },
  smoked:       { axes: ['bitter_char', 'umami'], nudge: 2 },
  'wood fired': { axes: ['bitter_char'], nudge: 2.5 },
  'wood-fired': { axes: ['bitter_char'], nudge: 2.5 },
  'char-grilled': { axes: ['bitter_char'], nudge: 2.5 },
  charcoal:     { axes: ['bitter_char'], nudge: 2.5 },
  roasted:      { axes: ['bitter_char', 'sweet'], nudge: 1 },
  'dark roast': { axes: ['bitter_char'], nudge: 2 },
  bitter:       { axes: ['bitter_char'], nudge: 2 },
  espresso:     { axes: ['bitter_char', 'umami'], nudge: 2 },
  coffee:       { axes: ['bitter_char', 'sweet'], nudge: 1.5 },
  bittersweet:  { axes: ['bitter_char', 'sweet'], nudge: 1.5 },
  wok_hei:      { axes: ['bitter_char', 'umami'], nudge: 2 },
  'wok-fried':  { axes: ['bitter_char', 'umami'], nudge: 1.5 },
  blackened:    { axes: ['bitter_char', 'spice'], nudge: 2 },
  caramelized:  { axes: ['bitter_char', 'sweet'], nudge: 1.5 },
  maillard:     { axes: ['bitter_char', 'umami'], nudge: 1.5 },
  seared:       { axes: ['bitter_char', 'umami'], nudge: 1.5 },
  bbq:          { axes: ['bitter_char', 'sweet', 'umami'], nudge: 1.5 },

  // ── Bright / Acid ────────────────────────────────────────────────────────
  lemon:        { axes: ['bright_acid'], nudge: 1.5 },
  lime:         { axes: ['bright_acid'], nudge: 1.5 },
  vinegar:      { axes: ['bright_acid'], nudge: 2 },
  pickled:      { axes: ['bright_acid'], nudge: 2 },
  brined:       { axes: ['bright_acid'], nudge: 1.5 },
  fermented:    { axes: ['bright_acid', 'umami'], nudge: 1.5 },
  citrus:       { axes: ['bright_acid'], nudge: 1.5 },
  yuzu:         { axes: ['bright_acid'], nudge: 2 },
  ponzu:        { axes: ['bright_acid', 'umami'], nudge: 2 },
  tamarind:     { axes: ['bright_acid', 'sweet'], nudge: 1.5 },
  sumac:        { axes: ['bright_acid'], nudge: 2 },
  capers:       { axes: ['bright_acid', 'umami'], nudge: 1.5 },
  cornichon:    { axes: ['bright_acid'], nudge: 1.5 },
  giardiniera:  { axes: ['bright_acid', 'spice'], nudge: 1.5 },
  tomato:       { axes: ['bright_acid', 'sweet', 'umami'], nudge: 1 },
  buttermilk:   { axes: ['bright_acid', 'creamy'], nudge: 1.5 },
  yogurt:       { axes: ['bright_acid', 'creamy'], nudge: 1 },
  labneh:       { axes: ['bright_acid', 'creamy'], nudge: 1.5 },
  shrub:        { axes: ['bright_acid', 'sweet'], nudge: 1.5 },
  sourdough:    { axes: ['bright_acid'], nudge: 1.5 },
  preserved_lemon: { axes: ['bright_acid', 'umami'], nudge: 2 },
  verjuice:     { axes: ['bright_acid'], nudge: 1.5 },

  // ── Sweet ────────────────────────────────────────────────────────────────
  sweet:        { axes: ['sweet'], nudge: 1.5 },
  caramel:      { axes: ['sweet', 'bitter_char'], nudge: 2 },
  honey:        { axes: ['sweet'], nudge: 1.5 },
  maple:        { axes: ['sweet'], nudge: 1.5 },
  mirin:        { axes: ['sweet', 'umami'], nudge: 1.5 },
  hoisin:       { axes: ['sweet', 'umami'], nudge: 1.5 },
  teriyaki:     { axes: ['sweet', 'umami'], nudge: 1.5 },
  'sweet soy':  { axes: ['sweet', 'umami'], nudge: 1.5 },
  'palm sugar': { axes: ['sweet'], nudge: 1.5 },
  molasses:     { axes: ['sweet', 'bitter_char'], nudge: 1.5 },
  mango:        { axes: ['sweet', 'bright_acid'], nudge: 1.5 },
  coconut_sugar: { axes: ['sweet'], nudge: 1.5 },
  glazed:       { axes: ['sweet', 'bitter_char'], nudge: 1 },
  candied:      { axes: ['sweet', 'bitter_char'], nudge: 1.5 },

  // ── Crispy ────────────────────────────────────────────────────────────────
  crispy:       { axes: ['crispy'], nudge: 2.5 },
  crunchy:      { axes: ['crispy'], nudge: 2 },
  fried:        { axes: ['crispy', 'richness'], nudge: 2 },
  'deep fried': { axes: ['crispy', 'richness'], nudge: 2.5 },
  'pan fried':  { axes: ['crispy'], nudge: 2 },
  'stir fried': { axes: ['crispy', 'bitter_char'], nudge: 1 },
  tempura:      { axes: ['crispy'], nudge: 2.5 },
  battered:     { axes: ['crispy'], nudge: 2 },
  breadcrumbs:  { axes: ['crispy'], nudge: 1.5 },
  panko:        { axes: ['crispy'], nudge: 2 },
  crusted:      { axes: ['crispy'], nudge: 1.5 },
  shattering:   { axes: ['crispy'], nudge: 2.5 },
  crackle:      { axes: ['crispy'], nudge: 2 },
  toast:        { axes: ['crispy', 'bitter_char'], nudge: 1.5 },
  toasted:      { axes: ['crispy', 'bitter_char'], nudge: 1 },

  // ── Silky / Creamy ───────────────────────────────────────────────────────
  silky:        { axes: ['silky', 'creamy'], nudge: 2.5 },
  velvety:      { axes: ['silky', 'creamy'], nudge: 2.5 },
  smooth:       { axes: ['silky', 'creamy'], nudge: 1.5 },
  creamy:       { axes: ['creamy', 'richness'], nudge: 2.5 },
  mousse:       { axes: ['silky', 'creamy', 'richness'], nudge: 2 },
  custard:      { axes: ['silky', 'creamy', 'sweet'], nudge: 2 },
  pudding:      { axes: ['silky', 'creamy', 'sweet'], nudge: 2 },
  burrata:      { axes: ['creamy', 'richness', 'silky'], nudge: 2.5 },
  mozzarella:   { axes: ['creamy', 'richness'], nudge: 1.5 },
  ricotta:      { axes: ['creamy', 'richness'], nudge: 1.5 },
  mascarpone:   { axes: ['creamy', 'richness', 'sweet'], nudge: 2 },
  creme_brulee: { axes: ['silky', 'creamy', 'sweet', 'bitter_char'], nudge: 2 },
  panna:        { axes: ['silky', 'creamy'], nudge: 2.5 },
  silken:       { axes: ['silky'], nudge: 2.5 },
  bisque:       { axes: ['creamy', 'richness', 'umami'], nudge: 2 },

  // ── Chewy ────────────────────────────────────────────────────────────────
  chewy:        { axes: ['chewy'], nudge: 2.5 },
  'al dente':   { axes: ['chewy'], nudge: 2 },
  noodles:      { axes: ['chewy'], nudge: 1 },
  pasta:        { axes: ['chewy'], nudge: 1 },
  dumpling:     { axes: ['chewy', 'silky'], nudge: 1.5 },
  bouncy:       { axes: ['chewy'], nudge: 2 },
  mochi:        { axes: ['chewy', 'sweet'], nudge: 2.5 },
  springy:      { axes: ['chewy'], nudge: 1.5 },
  squid:        { axes: ['chewy', 'umami'], nudge: 1.5 },
  octopus:      { axes: ['chewy', 'umami'], nudge: 1.5 },
  calamari:     { axes: ['chewy', 'umami'], nudge: 1.5 },
  abalone:      { axes: ['chewy', 'umami'], nudge: 2 },
}
